apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  labels:
    app: node-app
spec:
  replicas: 2 #The number of pods to be created in the Kubernetes cluster for the node.js application container
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app 
    spec:
      containers:
      - name: node-app #The name of the node.js application container
        image: bravinwasike/react-app:latest #The Docker image for building the node.js application container
        ports:
        - containerPort: 8080 #The port for the node.js application   container